#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

get_eq_options "$@"

if [[ $EQ_LOGIN = false || -z "$EQ_LOGIN" ]]; then
    printf "\nYou must provide an account login with -l LOGINACCOUNT\n\n"
    exit 1
fi

log "DATABASE" "Promoting $EQ_LOGIN to GM"
eq_account_status "$EQ_LOGIN" 255

