#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

get_options "$@"

pushd .

SERVERDIR=$([ ! -z "$OPT_DIR" ] && echo "$OPT_DIR" || echo "$QQDIR/source/EQMacEmu")

if [ ! -d "$SERVERDIR" ]; then
    log "BUILD" "Directory $SERVERDIR doesn't exist"
    exit 1
fi

cd $SERVERDIR

NPROC=$(nproc)

if [ "$OPT_CORES" != false ] && [ ! -z "$OPT_CORES" ]; then
    log "BUILD" "Forcing CPU cores to $OPT_CORES"
    NPROC=$OPT_CORES
fi

if [[ "$NPROC" -gt 8 ]]; then
    log "BUILD" "Locking excessive CPU cores to only 8"
    NPROC=8
fi

log "BUILD" "Using source in $SERVERDIR"

log "BUILD" "Generating make files..."
exec_cmd_as $QQUSER "cmake -DCMAKE_CXX_FLAGS='-w -fcompare-debug-second' -G 'Unix Makefiles' ."

log "BUILD" "Starting build with $NPROC threads... (this may take some time for the initial build)"
exec_cmd_as $QQUSER "make -j$NPROC"

popd
