#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

SOURCEDIR="$QQDIR/source"

if [ "$OPT_CLEAN" = true ]; then
    log "SOURCE" "Cleaning repos..."
    exec_cmd_as $QQUSER "rm -rf $SOURCEDIR"
fi

log "SOURCE" "Creating source directory..."
exec_cmd_as $QQUSER "mkdir -p $SOURCEDIR"

if [ ! -d "$SOURCEDIR" ]; then
    log "SOURCE" "Directory $SOURCEDIR doesn't exist"
    exit 1
fi

pushd .

cd $SOURCEDIR

if [ -z "$SERVERREPO" ]; then 
    SERVERREPO=$DEFAULT_SERVERREPO
fi

if [ ! -d "$SOURCEDIR/EQMacEmu" ]; then 
    log "SOURCE" "Cloning server repo..."
    exec_cmd_as $QQUSER "git clone $SERVERREPO EQMacEmu 2>/dev/null"
fi

if [ ! -d "$SOURCEDIR/quests" ]; then 
    log "SOURCE" "Cloning quests repo..."
    exec_cmd_as $QQUSER "git clone https://github.com/SecretsOTheP/quests.git quests 2>/dev/null"
fi

if [ ! -d "$SOURCEDIR/Maps" ]; then 
    log "SOURCE" "Cloning maps repo..."
    exec_cmd_as $QQUSER "git clone https://github.com/EQMacEmu/Maps.git Maps 2>/dev/null"
fi

popd

