#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

get_options "$@"

pushd .

BINDIR="$QQDIR/bin"
SERVERDIR=$($OPT_DIR && echo "$OPT_DIR" || echo "$QQDIR/source/EQMacEmu")

if [ ! -d "$BINDIR" ]; then
    log "BUILD" "Directory $BINDIR doesn't exist, creating it."
    exec_cmd_as $QQUSER "mkdir -p $BINDIR" 
fi

if [ ! -d "$SERVERDIR" ]; then
    log "BUILD" "Directory $SERVERDIR doesn't exist"
    exit 1
fi

cd $BINDIR

log "INSTALL" "Cleaning up bin directory"
exec_cmd_as $QQUSER "find $BINDIR -type f ! -name .gitkeep -delete"

### Possibly use OPT_CLEAN to purge logs and shared here, but an active running server uses the shared folder.
### Shared folder will be rewritten on quick-quarm restart

log "INSTALL" "Copy build binaries to bin directory"
exec_cmd_as $QQUSER "cp $SERVERDIR/bin/* ."

log "INSTALL" "Create logs and shared directories"
exec_cmd_as $QQUSER "mkdir -p logs"
exec_cmd_as $QQUSER "mkdir -p shared"

log "INSTALL" "Link source directory"
exec_cmd_as $QQUSER "ln -fs ../source"

log "INSTALL" "Link quests and maps directories"
exec_cmd_as $QQUSER "ln -fs ../source/Maps"
exec_cmd_as $QQUSER "ln -fs ../source/quests"

log "INSTALL" "Copy in auxillary configuration files"
exec_cmd_as $QQUSER "cp $SERVERDIR/loginserver/login_util/*.conf ."
exec_cmd_as $QQUSER "cp $SERVERDIR/utils/patches/*.conf ."

. "$QQDIR/scripts/update-config"

popd
