#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

exit_if_not_root

DBDIR=$QQDIR/db
FILESDIR=$QQDIR/files
SERVERDIR=$QQDIR/source/EQMacEmu
DATADIR=$SERVERDIR/utils/sql/database_full

LATESTDB=$(ls -Art $DATADIR | tail -n 1)

pushd .

cd $DBDIR

log "DATABASE" "Extracting latest database files..."
exec_cmd_as $QQUSER "tar zxf $DATADIR/$LATESTDB" 

MYSQLCS="-u$DBUSER -p$DBPASS $DBNAME"

log "DATABASE" "Setup database and tables..."
mysql_exec_as "root" "" "DROP DATABASE IF EXISTS $DBNAME; CREATE DATABASE $DBNAME"
mysql_import "$MYSQLCS" "$DBDIR/login_tables_*.sql"
mysql_import "$MYSQLCS" "$DBDIR/player_tables_*.sql"
mysql_import "$MYSQLCS" "$DBDIR/quarm_*.sql"
mysql_import "$MYSQLCS" "$DBDIR/data_tables_*.sql"
mysql_import "$MYSQLCS" "$SERVERDIR/loginserver/login_util/tblloginserversettings.sql"
mysql_import "$MYSQLCS" "$SERVERDIR/loginserver/login_util/updates/2023_07_27_tblLoginServerAccounts.sql"
mysql_import "$MYSQLCS" "$FILESDIR/update_settings.sql"

popd