#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

mkdir -p $BASEDIR/source

pushd .

cd $BASEDIR/source

git clone https://github.com/SecretsOTheP/EQMacEmu.git
git clone https://github.com/SecretsOTheP/quests.git
git clone https://github.com/EQMacEmu/Maps.git

popd

