#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

export LAUNCHEREXE="$BINDIR/zone"

if [ -z "$PUBLICIP" ]; then
    export PUBLICIP=$HOSTIP
fi

log "CONFIG" "Updating eqemu_config.json"
exec_cmd_as $QQUSER "envsubst < $TEMPLATE_EQEMUCONFIG > $BINDIR/eqemu_config.json"

log "CONFIG" "Updating login.json"
exec_cmd_as $QQUSER "envsubst < $TEMPLATE_LOGININI > $BINDIR/login.json"

