#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

exit_if_not_root

get_options "$@"

DBEXISTS=$(mysql_db_exists)

if [ ! $DBEXISTS ]; then
    printf "\nDatabase '$DBNAME' does not exist, did you run setup?\n"
    exit
fi

if [ "$OPT_DEBUG" = true ]; then 
    enable_debug
fi

printf "\nBeginning update:\n"

. "$QQDIR/scripts/update-permissions"
. "$QQDIR/scripts/update-source" "$@"
. "$QQDIR/scripts/update-database"
. "$QQDIR/scripts/build-source" "$@"
. "$QQDIR/scripts/install-bin" "$@"

printf "\n\n===== UPDATED!!! =====\n\nIn order to complete the update, you need to restart the Quick Quarm service.\nKeep in mind that the server \
will come down, so anyone logged in will be disconnected.\nThe restart command takes a few minutes to finish, so be patient.\n\n \
* sudo systemctl restart quick-quarm.target\n\n"