#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

log "SOURCE" "Verifying source directory exists"
exec_cmd_as $QQUSER "mkdir -p $QQDIR/source"

pushd .

if [ $SERVERREPO = $DEFAULT_SERVERREPO ]; then
    log "SOURCE" "Updating server repo"
    cd $QQDIR/source/EQMacEmu
    exec_cmd_as $QQUSER "git reset --hard HEAD; git pull"
else
    log "SOURCE" "Not updating custom source repo"
fi

log "SOURCE" "Updating quests repo"
cd $QQDIR/source/quests
exec_cmd_as $QQUSER "git reset --hard HEAD; git pull"

log "SOURCE" "Updating maps repo"
cd $QQDIR/source/Maps
exec_cmd_as $QQUSER "git reset --hard HEAD; git pull"

popd
