#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

if [ ! -d $SERVERDIR ] || [ ! -d $QUESTDIR ] || [ ! -d $MAPSDIR ]; then
    . "$QQDIR/scripts/download-source"
fi

log "SOURCE" "Verifying source directory exists"
exec_cmd_as $QQUSER "mkdir -p $QQDIR/source"

pushd .

if [ $SERVERREPO = $DEFAULT_SERVERREPO ]; then
    log "SOURCE" "Updating server repo"
    cd $SERVERDIR
    exec_cmd_as $QQUSER "git reset --hard origin/main; git pull"
else
    log "SOURCE" "Not updating custom source repo"
fi

log "SOURCE" "Updating quests repo"
cd $QUESTSDIR
exec_cmd_as $QQUSER "git reset --hard origin/main; git pull"

log "SOURCE" "Updating maps repo"
cd $MAPSDIR
exec_cmd_as $QQUSER "git reset --hard origin/main; git pull"

popd
