#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

mkdir -p $BASEDIR/source

pushd .

cd $BASEDIR/source/EQMacEmu
git pull

cd $BASEDIR/source/quests
git pull

cd $BASEDIR/source/Maps
git pull

popd
