#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

export LAUNCHEREXE="$QQDIR/bin/zone"

log "CONFIG" "Updating eqemu_config.json"
exec_cmd_as $QQUSER "envsubst < $TEMPLATE_EQEMUCONFIG > $QQDIR/bin/eqemu_config.json"

log "CONFIG" "Updating login.ini"
exec_cmd_as $QQUSER "envsubst < $TEMPLATE_LOGININI > $QQDIR/bin/login.ini"

