#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

DBDIR=$QQDIR/db
SERVERDIR=$QQDIR/source/EQMacEmu
DATADIR=$SERVERDIR/utils/sql/database_full

LATESTDB=$(ls -Art $DATADIR | tail -n 1)

pushd .

if [ ! -d "$DBDIR" ]; then
    log "DATABASE" "Directory $DBDIR doesn't exist"
    exit 1
fi

cd $DBDIR

log "DATABASE" "Extracting latest database files ($LATESTDB)..."
exec_cmd_as $QQUSER "tar zxf $DATADIR/$LATESTDB" 

log "DATABASE" "Update database and tables..."
mysql_import "$DBDIR/drop_system.sql"
mysql_import "$DBDIR/quarm_*.sql"

popd
